version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 8080:8080
        volumes: 
            - ./src:/app/src
            - ./config.dev.json:/etc/neuron_buildbot/config.json
        secrets:
            - neuron_buildbot

secrets:
    neuron_buildbot:
        file: ./secrets.dev.json
