version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 8080:8080
        volumes: 
            - ./src:/app/src
