FROM nixos/nix
WORKDIR /app

# Update nix
RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update

# install
ENV NODE_VERSION 14_x
RUN nix-env -iA nixpkgs.nodejs-${NODE_VERSION}

# install tini
ENV TINI_VERSION 0.19.0
RUN nix-env --install tini-${TINI_VERSION}
ENTRYPOINT ["tini", "--"]

# install neuron
ENV NEURON_VERSION 1d4656c06a896f42b2e644a4358c5259c7f5594e
RUN nix-env -iA cachix -f https://cachix.org/api/v1/install
RUN cachix use srid
RUN nix-env -if https://github.com/srid/neuron/archive/${NEURON_VERSION}.tar.gz

# install git for debugging
RUN apk add git

# install application
COPY package.json .
COPY package-lock.json .
RUN npm install

COPY nodemon.json .
COPY tsconfig.json .

COPY src/ ./src
CMD [ "npm", "run", "watch" ]
